version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/e2e:latest
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm install wait-on
            npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
      - run:
          name: Run Tests
          command: |
            npm run start

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo /videos;
            mkdir /multiple-results;
            echo /multiple-results/videos;
      - store_artifacts:
          path: /videos
          destination: /multiple-results
      - store_artifacts:
          path: /multiple-results

workflows:
  version: 2
  full:
    jobs:
      - build