version: 2.1

jobs:
  build:
    docker:
      - image: cristircr/e2e:latest
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install wait-on
            npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
            cypress install
      - run:
          name: Run Tests
          command: |
            npx cypress run --record --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"
      - run:
          name: Merge Reports
          command: |
            npx mochawesome-merge --reportDir cypress/report/mochawesome-report > cypress/report/mochawesome.json

workflows:
  version: 2
  full:
    jobs:
      - build