version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - attach_workspace:
          at: ~/cypress-environment/
      - checkout
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install --save-dev cypress
      - run:
          name: Start Application Server
          command: npm start
          background: true
      - run:
          name: Verify Cypress
          command: npx cypress verify
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Cypress tests
          no_output_timeout: 5m
          command: npx cypress run
workflows:
  build:
    jobs:
      - test
