version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/e2e:latest
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
            npm install wait-on
            npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
      - run:
          name: Run Tests
          command: |
            npm run start
      - store_artifacts:
          path: cypress/videos
          destination: multiple-results

workflows:
  version: 2
  full:
    jobs:
      - build