version: 2.1
orbs:
  cypress: cypress-io/cypress@1.19.2
workflows:
  commit:
    jobs:
      - cypress/install:
          install-command: 'npm install --no-optional --unsafe-perm'

      - cypress/run:
          requires:
            - cypress/install
          start: 'lerna run start --parallel'
          install-command: 'npm install --no-optional --unsafe-perm'