version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      #- cypress/install
      - run:
          name: Start cy:pipeline server
          command: npm start
          working_directory: ~/repo
          background: true
      - run:
          name: Run Cypress tests
          command: npm test
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start and test
          command: npm run ci
