version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/root/
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Start and test
          command: npm run test
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  full:
    jobs:
      - build