version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor

    working_directory: ~/cypress-environment/

    steps:
      - checkout

      - attach_workspace:
          at: ~/cypress-environment/

      # Install dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Cypress
          command: npm install --save-dev cypress

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run:
          name: Run Mocha Tests
          command: npm run test -- cypress/integration/

      - run:
          name: Run Cypress Tests
          command: npm run cypress:run

# Store test artifacts and results
      - store_artifacts:
          path: results
          destination: test_results
      - store_test_results:
          path: results