version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  install:
    executor: cypress/default
    steps:
      - cypress/install:
          install-browsers: true
      - persist_to_workspace:
          root: ~/cypress-environment/
          paths:
            - .cache/Cypress
            - project
  run-tests:
    executor: cypress/default
    parallelism: 10
    steps:
      - run: echo "This step assumes dependencies were installed using the cypress/install job"
      - attach_workspace:
          at: ~/cypress-environment/
      - cypress/run-tests:
          cypress-command: 'npx cypress run --parallel --record'
          start-command: 'npm run start'
workflows:
    version: 2
    full:
      jobs:
      - install
      - run-tests