version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:node14.16.0-chrome90-ff88
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/cypress-environment/
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm i npm@latest
      - run: npm install --frozen-lockfile
      - run: npm install --save-dev mocha mocha-multi-reporters mocha-junit-reporter
      - run: npm install --save-dev cypress
      - run: npm cache clean --force
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: ~/junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: cypress run --reporter mocha-multi-reporters --reporter-options configFile=config.json
      - store_test_results:
          path: ~/multiple-results
      - store_artifacts:
          path: ~/cypress/videos
      - store_artifacts:
          path: ~/cypress/screenshots