version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/cypress-environment/
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - run: npm install --save-dev cypress
      - run: npm cache clean --force
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: ~/cypress-environment/junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: ~/cypress-environment/multiple-results
      - store_artifacts:
          path: ~/cypress-environment/cypress/videos
      - store_artifacts:
          path: ~/cypress-environment/cypress/screenshots