version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Clear NPM cache
          command: npm cache clean --force
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start and test
          command: npm run ci
