version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/cypress-environment/ 
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Start cy:pipeline server
          command: npm start
          working_directory: ~/cypress-environment/
          background: true
      - run:
          name: Run Cypress tests
          command: npm test
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Start and test
          command: npm run ci
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  full:
    jobs:
      - build